# Generated by Django 5.1.5 on 2025-03-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_category_remove_notification_link_remove_users_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('reebok', 'Reebok'), ('under_armour', 'Under Armour'), ('new_balance', 'New Balance'), ('wilson', 'Wilson'), ('speedo', 'Speedo'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Key product features and specifications'),
        ),
    ]
